### Site Settings ###
repository : YoussefRaafatNasry/YoussefRaafatNasry.github.io


### Accounts ###
author:
  codeforces : YoussefRaafatNasry
  linkedin   : YoussefRaafatNasry
  email      : YoussefRaafatNasry@gmail.com

### Collections ###
collections:
 - icons